name: GH Advies
favicon: null
layout_spectrum: 0.7261250296141952
typography_spectrum: 0.75077
title: 'Gerbert Hupkens. Financieel Advies & Account Management'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8f1f8'
    - '#74a8cf'
    - '#c8dbea'
    - '#366e93'
    - '#00183d'
  brandStrength: 0.7174962947610766
  lightness: 0.4991120758932084
  saturation: 0.96555489115417
  rhythmicContrast: 0.9254534570500255
purpose: []
